/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FootprintPanel: typeof import('./src/components/FootprintPanel.vue')['default']
    InputBar: typeof import('./src/components/InputBar.vue')['default']
    MessageBubble: typeof import('./src/components/MessageBubble.vue')['default']
    QuestionPanel: typeof import('./src/components/QuestionPanel.vue')['default']
    RightPanel: typeof import('./src/components/RightPanel.vue')['default']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SideChatPanel: typeof import('./src/components/SideChatPanel.vue')['default']
    ThinkingIndicator: typeof import('./src/components/ThinkingIndicator.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    ToolExecution: typeof import('./src/components/ToolExecution.vue')['default']
  }
}
